# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuartel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id_cuerpo', models.AutoField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Soldado',
            fields=[
                ('id_soldado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('grado', models.CharField(max_length=40)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuartel.Compania')),
                ('cuerpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldado.Cuerpo')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldado.Servicio')),
            ],
        ),
    ]
