# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-21 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id_compania', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cuartel',
            fields=[
                ('id_cuartel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
